### ISSUE TITLE
Add Python Type Hints

### ISSUE THREAD

**Issue by mgear2** [mgear2/undervoid#7]
Justification:
-[PEP 484](https://www.python.org/dev/peps/pep-0484/) provided semantics for type hints/annotations in Python 3
-Implementing type hints for functions/methods will help greatly with code clarity and readability

**Comment by trivediavinash** [comment]
can you assign this to me

**Comment by trivediavinash** [comment]
@mgear2  Hey thanks for assigning this issue to me .I was going through the code and couldn't find the exact code where i have to add hints/annotations  .Could you please guide me in this .Thanks

**Comment by mgear2** [comment]
Following #10 type hints are implemented for all applicable classes.
